name: CI

# Controls when the action will run - on push or pull request events but only for the master branch or manually triggered.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.14.0'
      - name: Build Project
        run: go build cmd/karetaker/karetaker.go
